### ISSUE TITLE
It should not stop the CI / exit = 0

### ISSUE THREAD

**Issue by pascalandy** [hadolint/hadolint-action#17]
I use this action to keep trace of best practices. It should not stop the CI . Is is possible ?

Thanks!

**Comment by pascalandy** [comment]
Same error here:

## yml

```
      - 
        name: Saving Lighthouse Audit Artifacts
        uses: actions/upload-artifact@master
        with:
          name: lighthouse-artifacts
          path: './results'
```

## logs

```
Warning: secret not defined; PR comment reporting disabled.
CDP: network conditions set to WPT threegfast profile.
CDP: network conditions set to WPT threegfast profile.
CDP: network conditions set to WPT threegfast profile.
CDP: network conditions set to WPT threegfast profile.
CDP: network conditions set to WPT threegfast profile.

[Lighthouse](https://developers.google.com/web/tools/lighthouse/) report for the changes in this PR:

WPT Profile: threegfast

| Category | Score |
| ------------- | ------------- |
| Performance | 100 | 
| Accessibility | 87 | 
| Best Practices | 100 | 
| SEO | 90 | 
| Progressive Web App | 56.00000000000001 | 

| Measure | Timing |
| ------------- | ------------- |
| First Contentful Paint | 1.3 s | 
| First Meaningful Paint | 1.3 s | 
| Max Potential First Input Delay | 260 ms | 
| Time to Interactive | 2.0 s | 
| First CPU Idle | 2.0 s | 
| Speed Index | 1.7 s | 

_Tested with Lighthouse v5.6.0 via [lighthouse-action](https://github.com/justinribeiro/lighthouse-action)_
Error: Cannot read property 'comments_url' of undefined
```
