### ISSUE TITLE
Support -f parameter

### ISSUE THREAD

**Issue by fglaeser** [hadolint/hadolint-action#18]
Hi I would like to get from the action the report in checkstyle format in order to integrate hadolint with sonarqube, it would be nice to have this option available in the action as a parameter, also the output file name.

```yaml

steps:
    - uses: brpaz/hadolint-action@v1.2.1
      with:
        dockerfile: Dockerfile
        format: checkstyle | json | etc
        outputPath: report.json
```

Thanks
