### ISSUE TITLE
Error: No hadolint failure but Actions job fails

### ISSUE THREAD

**Issue by gakugaku** [hadolint/hadolint-action#60]
No hadolint failure but Actions job fails when executing below actions.

Execution log

![error](https://user-images.githubusercontent.com/14232275/169355632-d531ab4c-3c5b-4643-a63d-f3bd28bb3d6a.png)

Actions yaml (part of hadolint job)

```yaml
  lint-dockerfile:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: hadolint (dockerfile linter)
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          recursive: true
```

---
Workaround: Actions success when setting `failure-threshold: "warning"` option.
But even if hadolint fails with info severity, Actions job will succeed😢. 

![error2](https://user-images.githubusercontent.com/14232275/169359934-019a855c-0136-4d07-9063-3b9995369075.png)

```yaml
  lint-dockerfile:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: hadolint (dockerfile linter)
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          recursive: true
          failure-threshold: "warning"
```

**Comment by hatamiarash7** [comment]
I have this problem too

**Comment by FrankGiesecke** [comment]
Same problem an currently no solution 😢

**Comment by FrankGiesecke** [comment]
The problem seems to be, that some errors/warnings/infos are not displayed in the log.
I have a [Dockerfile](https://github.com/final-gene/docker-hub-heroku-cli/blob/main/Dockerfile) which doesn't contain any ignore statements.
In my first run, my `.hadolint.yaml` only contains the exclusion for `DL3018`.
If I run Hadolint from CLI, I get the message:
```
Dockerfile:13 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
```
But in the CI, no message is displayed but the step fails.

If I add the exclusion for `DL3059`, the CI step succeeds.

**Comment by erzz** [comment]
I hate to leave me too messages - but me too :)

**Comment by ViacheslavKudinov** [comment]
Same here.
Had to switch back to v2.0.0, this works fine.

**Comment by ReenigneArcher** [comment]
I've been experiencing this same issue for a couple of months. Is this project still maintained? Last activity seems to be in May.

**Comment by ReenigneArcher** [comment]
I found that if you re-run the job with debug logging enabled you will see some output.

**Comment by brpaz** [comment]
For me it worked to set `failure-threshold` to `error` or `warning`

According to the documentation, the default is `info`. I don´t know how this works internally in Hadolint, but my theory, is that `info` is making the pipeline fail with any output, even if it has no errors.

Ex:

```yaml
 - name: Lint Dockerfile
    uses: hadolint/hadolint-action@v3.0.0
    with:
      dockerfile: Dockerfile
      failure-threshold: error
```

**Comment by maxhelias** [comment]
Not sure but this seems to be related to https://github.com/hadolint/hadolint-action/pull/55

**Comment by rene-bos** [comment]
This issue has been fixed by the 3.0.0 release for us (we also pinned at 2.0.0 to avoid having this problem).

**Comment by maxhelias** [comment]
I still have it on 3.0.0 and even on master : https://github.com/dunglas/symfony-docker/actions/runs/3765268860/jobs/6400565741

**Comment by humphd** [comment]
Setting `v3.0.0` up tonight, and it fails like many people are mentioning above, unless I explicitly include `failure-threshold: error`:

```yml
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Hadolint on Dockerfile
        uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: Dockerfile
          # it will fail with no error if I omit this...
          failure-threshold: error
```
