### ISSUE TITLE
How do I ignore certain problems?

### ISSUE THREAD

**Issue by tschm** [hadolint/hadolint-action#8]
e.g. i would love to do something along these lines

```
name: Lint Dockerfile

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
          ignore: "DL3013"
```

Who can I achieve that?
