### ISSUE TITLE
Dockerfile is a directory

### ISSUE THREAD

**Issue by apoorva2809** [hadolint/hadolint-action#81]
```
- name: Run Hadolint on Dockerfiles
      id: hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        output-file: hadolintresult.json
        recursive: true
        no-fail: true
        format: json
        
```
        
 I have some usecases in which Dockerfile is a directory and inside that we have dockerfile , but it fails as soon as it founds Docker name directory instead it should ignore those
